language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
- pip install codecov
- pip install requests
install:
- python ./setup.py install
- python get-iaca.py --i-accept-the-What-If-Pre-Release-License-Agreement-and-please-take-my-soul
  lin64
cache: pip
before_script:
- export PATH=$PATH:$PWD/iaca-lin64/
script:
- coverage run -p tests/all_tests.py
- coverage run -p `which kerncraft` --help
after_success:
- coverage combine
- codecov
deploy:
  provider: pypi
  user: travis.rrze-hpc
  password:
    secure: gf79TBwuYgcC1BazPC3sxF9tzmZFxJJUtGN+SZ8InfzKqUQ7aMn1xHOHq+/hpCItrGxwRfYQ/kemqzhFezmmh+wEn78zGHxKEezU4FQ4QtO5ZV+NOb/24wszDfx+dvICCCF9xfWVWXLB8QDTVKgodO4dw/6odE9/eIirnP92Wy7jmVcD8g2TkxNSBkj53yeqQ4T7Kir5yeN0D4v89DQ7r7SBTTjp8xTCgkwm5btvgdbLo9w+1lcgqcwGpBiOO5uPPap32GITjZB85SYkZ9WKPL0m6LlCZzk9ylr8gr5+r0OF5F5ZwBHsh3KRu64qWPdYqpZ6fJr7srgcwF803NjpooNF5WGUdr6focRH/M70TnkQJv70mN1nWCWKS06plP2l++4w4QdHgVFGLpSquXItCNsg2loFfTqEbo4HkFWiYh5ZgTaRW16JK5EbEC5hZ4S2oiUMdrWPPt0WPOCU+gcmTXcVdaxqSkJQJ5oP5pO6xrbvrEbNB3vi9iiyk0dnynaYsxOXnSdo00gq2xXDGL8zpkw2Ou0O13sSY5c1nqw0KGQb4Dzan31GacbCQN4frEJmlKapvtSS2PpNlXPvXzeeqDZaNQmxpqu3SVZaAm8JlEQb+JaE73jbz16q957rdJjDniQkOXVdbZipEnVwNc5dhEl7J6QQyRgNW7gsqOrGP9g=
  distributions: sdist bdist_wheel
  on:
    repo: RRZE-HPC/kerncraft
