language: python
python:
- '3.4'
- '3.5'
- '3.6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
- pip install codecov
- pip install requests
install:
- pip install -e .
- iaca_get --I-accept-the-Intel-What-If-Pre-Release-License-Agreement-and-please-take-my-soul
cache: pip
script:
- coverage run -p tests/all_tests.py
- coverage run -p `which kerncraft` --help
after_success:
- coverage combine
- codecov
deploy:
  provider: pypi
  user: travis.rrze-hpc
  password:
    secure: aWSruT3vVdvezXERBqxZumdnQHO8d2moOyjSw1oYPohUCRTP+JBlRK2ZuZbkA0jXKD7iS/DvASxXkyHsn/4I64ukbRsjnxvCqWnm5ujpomCP5LNy4exMdokRCYlLIrBMl90KIwRF2MJFFHYh/j90R61ZWX1HWIh66KQdmZuyA2OJ+J+g41etzT4KudB4gyvzhkr6mKxIvnqQxpIZWh9ZNbsFOLWn/k87Ei5c5LEtB9FbJ+g1MxyC/7+74u+gn3EY6lCBZ3EsUhzuZDngc/H0UlyOuJuc5llh/MA0K79HaS9bIx/WoU3Q0jeGmxi8xScmyjeo6XcnBUdpfLSlmPeP4GUFR/MLtYCMQwKb0rwnNRaM+BNyxVGDcRyDUyM/UiTRIN/hfzfyKp12OWMMKhCZ9u+YklQetSLVDnykP688hZpHBLlGJ/OPGOptk9huRByzrb7P6pnfZG46w1pB2KMsD/eATbgSWRaj5BIqU5c1VNAkHsR4cKklvMbR+GaFMpBLRN5PqxADico5JG8WQoMZ2pZ+JiSAK6FZPXl0LAAk0SU/3mAt10hQveNOhq9NNbRHsZc4HFXf1ilkn3NnXd7yoEzMzzLkZzbEKKVRB2HSkitxdSL5FZkFu4IncDH5zCyAB+VINt8k2JVjbFez1zXCgnPvJbrbK5jGigAsNvyUivs=
  distributions: sdist
  skip_existing: true
  skip_cleanup: true
  on:
    repo: RRZE-HPC/kerncraft
    tag: true
